### ISSUE TITLE
QGIS 2.18.16

### ISSUE THREAD

**Issue by Ettezaz** [3liz/QgisCadastrePlugin#125]
Depuis la mise à jour vers QGIS 2.18.16, il y a une erreur au démarrage de l'application.

> Impossible de charger l'extension cadastre provoque une erreur lors de l'appel de sa méthode classFactory() 
ImportError: No module named _psycopg 
Traceback (most recent call last):
  File "C:/OSGEO4W64/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/user/.qgis2/python/plugins\cadastre\__init__.py", line 26, in classFactory
    from cadastre_menu import cadastre_menu
  File "C:/OSGEO4W64/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/user/.qgis2/python/plugins\cadastre\cadastre_menu.py", line 30, in 
    from cadastre_dialogs import cadastre_common, cadastre_search_dialog, cadastre_import_dialog, cadastre_load_dialog, cadastre_option_dialog, cadastre_about_dialog, cadastre_parcelle_dialog, cadastre_message_dialog
  File "C:/OSGEO4W64/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/user/.qgis2/python/plugins\cadastre\cadastre_dialogs.py", line 41, in 
    from db_manager.db_plugins.postgis.connector import PostGisDBConnector
  File "C:/OSGEO4W64/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/OSGEO4W64/apps/qgis/./python/plugins\db_manager\db_plugins\postgis\connector.py", line 33, in 
    import psycopg2
  File "C:/OSGEO4W64/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4W64\apps\Python27\lib\site-packages\psycopg2\__init__.py", line 50, in 
  File "C:/OSGEO4W64/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named _psycopg
Version de Python : 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Version de QGIS : 2.18.16 Las Palmas, d473c3071a >

**Comment by mdouchin** [comment]
Bonjour,
Ce bug est apparu suite à la montée de version de QGIS 2.18.15 à 2.18.16 ?
Le plugin Cadastre utilise les outils du gestionnaire de bases de données de QGIS, qui utilisent psycopg pour se connecter aux bases PostgreSQL.

Pouvez vous essayer d'utiliser les outils de QGIS : Menu Base de données > Gestionnaire de base de données pour vous connecter à la base ?

**Comment by Ettezaz** [comment]
Bonjour,
Je n’avais pas la version 2.18.15, mais une 2.18 c'est certain, je ne sais plus laquelle.
Je vois bien les bases de données dans le Gestionnaire de BD.

Cependant, j'utilise très peu le plugin pour accéder à une base, il me sert uniquement à importer des EDIGEO pour en faire des SHP sur lesquels je peux travailler, la base de données n'est pour moi qu'une étape intermédiaire.

**Comment by mdouchin** [comment]
Et dans le gestionnaire de base de données, si vous voyiez bien les connections, est-ce que vous pouvez double-cliquer sur une connection et vous connecter, puis lister les objets (tables, etc.).

Sinon, faire un test : ouvrir la console python (menu Extension) et taper puis valider

```
import psycopg2
```

**Comment by Ettezaz** [comment]
Il y a du y avoir un bug lors de la mise à jour, le plugin Cadastre étant le seul qui ne fonctionnait pas, j'ai cru que c'était la cause.
Maintenant tout fonctionne ! Merci.
