### ISSUE TITLE
Import - Problème sur master

### ISSUE THREAD

**Issue by EtienneRouvin** [3liz/QgisCadastrePlugin#177]
**Description du bug**
En travaillant sur master, ce problème survient lorsque je lance l'import alors que cela fonctionne lorsque je reviens au commit 74b1be4977ddc42185c620d9b45bb9f410a6450e

**Log**
```
TypeError: setSearchPath() takes 2 positional arguments but 3 were given 
Traceback (most recent call last):
  File "C:/Users/e.rouvin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_dialogs.py", line 725, in processImport
    qi.importMajic()
  File "C:/Users/e.rouvin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_import.py", line 439, in importMajic
    self.executeSqlScript(s, True, 'constraints' in item)
  File "C:/Users/e.rouvin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_import.py", line 1076, in executeSqlScript
    sql = self.qc.setSearchPath(sql, self.dialog.schema)
TypeError: setSearchPath() takes 2 positional arguments but 3 were given


Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.4.4-Madeira Madeira, f6ddc62fdb 

Chemin Python :
C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python
C:/Users/e.rouvin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/e.rouvin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA~1\QGIS3~1.4\apps\Python37
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/e.rouvin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\e.rouvin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cadastre/forms

**Comment by rldhont** [comment]
Fixed by 5dc613232005bd087ddf11990147f94070c562ff

Available in next release
