### ISSUE TITLE
Création base spatialite impossible et importation stoppée à 50%

### ISSUE THREAD

**Issue by clemencegourlaouen** [3liz/QgisCadastrePlugin#232]
**Description du bug**

Bonjour, 
Je tente d'importer des données cadastrales suite à une modification sur la couche "parcelle" de mon projet qgis. Je n'ai plus accès à toutes les parcelles, la couche ayant été réduite suite à une suppression par erreur de ma part des parcelles.
J'ai bien les fichiers EDIGEO et MAJIC enregistrés sur mon ordinateur, mais lorsque je tente de les importer, 2 bugs se produisent : 
- BUG 1 : il m'est impossible de créer une nouvelle base spatialite 
- BUG 2 : j'ai déjà une connexion .squilte. Je tente donc de faire l'import avec cette dernière (qui a été modifiée suite à mon erreur je pense), mais à ce moment, l'import s'arrête à 50%.

Je viens de me mettre à QGIS. C'est tout nouveau pour moi, et j'ai fait afin de faire l'importation comme les vidéos trouvées sur internet. Quand j'ai eu le logiciel, le cadastre et les données étaient déjà sur mon ordinateur, c'est à cause d'une de mes modifications que cela ne fonctionne plus, mais je ne sais pas comment faire pour réparer cela.

J'espère être claire et qu'il ne manque pas des infos. Merci d'avance ! 

**Reproduire le bug**

BUG 1 : Ouvrir "importer des données", choisir spatialite et tenter de créer une nouvelle base spatialite --> RIEN NE SE PASSE

BUG 2 : Ouvrir "importer des données", choisir spatialite, choisir dans connexion "cadastre.sqilte" qui était déjà dans mon ordinateur. Bien mettre les chemins des fichiers EDIGEO et MAGIC, les sources, le département, etc.
Lancer l'import.

**Log**

Ci-dessous le log du plugin Cadastre

```
BUG 1 : Veuillez sélectionner une base de données

BUG 2 : INITIALISATION
Et la barre s'arrête à 50%
```
Recopier ci-dessous l'erreur Python de QGIS

```
BUG 1 : 
2020-05-05T18:24:01	1	Traceback (most recent call last):
			  File "C:/Users/Cl�mence/.qgis2/python/plugins\cadastre\cadastre_dialogs.py", line 673, in createNewSpatialiteDatabase
			    str(os.path.expanduser("~").encode('utf-8')).strip(' \t'),
			UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 11: ordinal not in range(128)

BUG 2 : 
2020-05-05T18:34:58	1	Traceback (most recent call last):
			  File "C:/Users/Cl�mence/.qgis2/python/plugins\cadastre\cadastre_dialogs.py", line 1155, in processImport
			    qi = cadastreImport(self)
			  File "C:/Users/Cl�mence/.qgis2/python/plugins\cadastre\cadastre_import.py", line 182, in __init__
			    self.beginImport()
			  File "C:/Users/Cl�mence/.qgis2/python/plugins\cadastre\cadastre_import.py", line 234, in beginImport
			    self.copyFilesToTemp(self.pScriptSourceDir, self.pScriptDir)
			  File "C:/Users/Cl�mence/.qgis2/python/plugins\cadastre\cadastre_import.py", line 909, in copyFilesToTemp
			    self.qc.updateLog(u'* Copie du répertoire %s' % source)
			UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 11: ordinal not in range(128)
			

```

**Environnement**
 - OS: Windows 10
 - Version de QGIS :  2.18.12
 - Version du plugin : 2.0

**Comment by clemencegourlaouen** [comment]
Bonjour à tous, 
j'ai trouvé mon problème : mon nom d'utilisateur étant "Clémence" avec un accent, cela faisait buguer le logiciel. Il faut travailler sur un autre compte, sans accent.

Merci !
Bonne journée à tous
