### ISSUE TITLE
Erreur d'éxécution du code Python lors de l'import de données EDIGEO et MAJIC

### ISSUE THREAD

**Issue by KevinChar** [3liz/QgisCadastrePlugin#259]
**Description du bug**
Bonjour,
Lors de l'import des données EDIGEO et MAJIC 2020 via le plugin cadastre, j'ai un message d'erreur m'indiquant un problème avec le fichier tarfile.py 

**Reproduire le bug**

1. Après avoir reçu les données, je renomme les fichiers MAJIC avant intégration.
2. Je paramètre la fenêtre d'import des données afin de créer une base Spatialite. Dans la partie paramètre, j'indique le département => 72, la direction => 0, version et année => 2020 Lot => 1 puis je lance l'import.
3. L'import s'arrête à 9% de l'extraction des fichiers EDIGEO.
4. La fenêtre d'erreur indiquée ci-dessous s'affiche.

**Log**

Une erreur est survenue lors de l'éxécution du code Python: 

tarfile.ReadError: file could not be opened successfully 
Traceback (most recent call last):
  File "C:/Users/k.char/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_dialogs.py", line 714, in processImport
    qi.importEdigeo()
  File "C:/Users/k.char/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_import.py", line 626, in importEdigeo
    self.unzipFolderContent(self.dialog.edigeoSourceDir)
  File "C:/Users/k.char/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_import.py", line 972, in unzipFolderContent
    with tarfile.open(z) as t:
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\tarfile.py", line 1576, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.10.10-A Coruña A Coruña, 8b051b9a43 

Chemin Python :
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/k.char/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/k.char/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/k.char/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\k.char\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cadastre\forms
C:\Users\k.char\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cadastre\forms

**Environnement**
 - OS: Windows 10 Professionnel
 - Version de QGIS :  3.10.10
 - Version du plugin : 1.9.0

Je vous remercie d'avance pour votre aide.
Cordialement,
Kévin

**Comment by mdouchin** [comment]
L'erreur est "parlante": `tarfile.ReadError: file could not be opened successfully ` -> Le plugin n'arrive pas à décompresser l'archive
Avez-vous testé de décompresser tous les fichiers EDIGEO dans un répertoire spécifique ? Attention à ne pas laisser des archives dans le répertoire contenant les fichiers décompressés
