### ISSUE TITLE
Le plugin écoute la création d'un nouveau projet et plante hors contexte Cadastre

### ISSUE THREAD

**Issue by Gustry** [3liz/QgisCadastrePlugin#276]
**Description du bug**

Vu chez quelqu'un ce matin, 
"Fichier" -> "Nouveau projet", il y a à chaque fois une erreur python qui s'affiche concernant un fichier SQLite invalide.
Mais il n'est pas en train de faire du Cadastre.

```
Une erreur est survenue lors de l'éxécution du code Python:

db_manager.db_plugins.plugin.ConnectionError: "C:/Users/XXXX/Desktop/Cadastre 2020/cadastre_2020.sqlite" non trouvé

Traceback (most recent call last):
  File "C:/Users/XXXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_menu.py", line 428, in onNewProjectCreated
    self.cadastre_search_dialog.checkMajicContent()
  File "C:/Users/XXXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_dialogs.py", line 1226, in checkMajicContent
    connector = CadastreCommon.getConnectorFromUri(self.connectionParams)
  File "C:/Users/XXXX/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_common_base.py", line 233, in getConnectorFromUri
    connector = SpatiaLiteDBConnector(uri)
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\db_manager\db_plugins\spatialite\connector.py", line 48, in __init__
    raise ConnectionError(QApplication.translate("DBManagerPlugin", '"{0}" not found').format(self.dbname))
db_manager.db_plugins.plugin.ConnectionError: "C:/Users/XXXX/Desktop/Cadastre 2020/cadastre_2020.sqlite" non trouvé
```

L'erreur vient de `onNewProjectCreated`.

**Environnement**
 - OS: Windows
 - Version de QGIS : 3.10
 - Version du plugin : la dernière

**Comment by Gustry** [comment]
Peut-être pas le top, mais il y a un historique dans le code.
Fait dans 1.10.2 d628367d77001ab49811b7a86e89022d1371c121

**Comment by MaelREBOUX** [comment]
merci pour la correction
