### ISSUE TITLE
[server] cadastre_export.py, line 145, 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by rldhont** [3liz/QgisCadastrePlugin#279]
**Description du bug**

```
09:21:15 CRITICAL cadastre[23213]: Unhandled exception:
Traceback (most recent call last):
  File "/srv/qgis/plugins/cadastre/server/cadastre_service.py", line 119, in executeRequest
    self.create_pdf(params, response, project)
  File "/srv/qgis/plugins/cadastre/server/cadastre_service.py", line 223, in create_pdf
    paths = qex.exportAsPDF()
  File "/srv/qgis/plugins/cadastre/cadastre_export.py", line 661, in exportAsPDF
    apath = self.exportItemAsPdf(self.comptecommunal)
  File "/srv/qgis/plugins/cadastre/cadastre_export.py", line 594, in exportItemAsPdf
    self.setComposerTemplates(comptecommunal)
  File "/srv/qgis/plugins/cadastre/cadastre_export.py", line 145, in setComposerTemplates
    comptecommunalAbrev = comptecommunal[9:]
TypeError: 'NoneType' object is not subscriptable
```

**Reproduire le bug**

Utilisation d'un projet avec lizmap et le module cadastre

**Log**

```
09:21:15 CRITICAL cadastre[23213]: Unhandled exception:
Traceback (most recent call last):
  File "/srv/qgis/plugins/cadastre/server/cadastre_service.py", line 119, in executeRequest
    self.create_pdf(params, response, project)
  File "/srv/qgis/plugins/cadastre/server/cadastre_service.py", line 223, in create_pdf
    paths = qex.exportAsPDF()
  File "/srv/qgis/plugins/cadastre/cadastre_export.py", line 661, in exportAsPDF
    apath = self.exportItemAsPdf(self.comptecommunal)
  File "/srv/qgis/plugins/cadastre/cadastre_export.py", line 594, in exportItemAsPdf
    self.setComposerTemplates(comptecommunal)
  File "/srv/qgis/plugins/cadastre/cadastre_export.py", line 145, in setComposerTemplates
    comptecommunalAbrev = comptecommunal[9:]
TypeError: 'NoneType' object is not subscriptable
```

**Environnement**
 - OS: Linux
 - Version de QGIS :  3.10
 - Version du plugin : 1.10.2

**Comment by MaelREBOUX** [comment]
C'est pour récupérer un bordereau parcellaire PDF depuis QGIS Server ?

**Comment by rldhont** [comment]
@MaelREBOUX oui

**Comment by Gustry** [comment]
Si on parle de ce bouton :  
![ksnip_20220124-172912](https://user-images.githubusercontent.com/1609292/150823560-19a1d00d-97e1-4e85-87f6-ca6cb616bc99.png)

J'ai bien le tableau qui s'affiche par la suite.

**Comment by Gustry** [comment]
Si on parle de ce bouton :  
![ksnip_20220124-172912](https://user-images.githubusercontent.com/1609292/150823560-19a1d00d-97e1-4e85-87f6-ca6cb616bc99.png)

J'ai bien le tableau qui s'affiche par la suite.

**Comment by Gustry** [comment]
Il y a un peu de refactoring de code côté serveur dans la version 1.14.0, avec un peu plus de log.
Si il est possible de tester cette version.
Je vais ajouter un garde fou pour la variable.
