### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9'

### ISSUE THREAD

**Issue by samuelDeom** [3liz/QgisCadastrePlugin#301]
**Description du bug**

Le plug in échoue à importer les données du millésime du 1er avril 2021 au format EDIGEO, visiblement pour un problème d'encodage, apparemment quelque soit la commune et le nom ou l'emplacement du répertoire contenant les données.

**Log**
```
Une erreur est survenue lors de l'éxécution du code Python: 

UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 25946: ordinal not in range(128) 
Traceback (most recent call last):
  File "/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cadastre/cadastre_dialogs.py", line 751, in processImport
    qi.installCadastreStructure()
  File "/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cadastre/cadastre_import.py", line 244, in installCadastreStructure
    self.replaceParametersInScript(s, replaceDict)
  File "/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cadastre/cadastre_import.py", line 1016, in replaceParametersInScript
    fout.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 25946: ordinal not in range(128)


Version de Python : 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
Version de QGIS : 3.16.7-Hannover Hannover, 607b44b1e0 
```

**Environnement**
 - OS: macOS Big Sur 11.3.1
 - Version de QGIS :  3.16.7-Hannover Hannover, 607b44b1e0
 - Version du plugin : 1.11.1

**Comment by Gustry** [comment]
Merci d'essayer la nouvelle version 1.13.2 et réouvrir si le problème persiste.
Je ne suis pas sur d'avoir corrigé le problème. Si le problème est toujours la, merci de donner la commune qui pose problème.

**Comment by samuelDeom** [comment]
Bonjour,
Problème corrigé après mise-à-jour.
Merci.
