### ISSUE TITLE
Erreur python pour les relevés parcellaires et de propriété

### ISSUE THREAD

**Issue by WSeb** [3liz/QgisCadastrePlugin#318]
**Description du bug**

Je rencontre des erreurs python (voir ci-dessous) lorsque j'utilise les boutons d'édition de relevés parcellaires ou de propriété du panneau de recherche du plugin.
Les tables semblent pourtant remplies correctement dans PostGIS et j’accède bien à ces relevés en passant par l’outil d’infos parcelles.

**Reproduire le bug**

Etapes pour reproduire le bug (remplacer)

1. Effectuer une recherche de parcelle ou de propriétaire depuis le panneau de recherche du plugin
2. Cliquer sur le bouton d'export de relevés parcellaire ou de propriété depuis ce même panneau

**Log**

Ci-dessous le log du plugin Cadastre

Je n'ai pas de fenêtre de log du plugin qui s'ouvre. Voici le le log de l'onglet "Messages" :

```
2021-09-02T17:08:33     WARNING    Erreur Python : Une erreur est survenue lors de l'éxécution du code Python: Voir le journal des erreurs Python pour plus de détails
```

Recopier ci-dessous l'erreur Python de QGIS

-	Lorsque je clique sur les boutons de relevé parcellaire  : 

```
2021-08-31T14:21:08     WARNING    Traceback (most recent call last):
              File "C:/Users/992607/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\dialogs\search_dialog.py", line 1237, in exportParcelle
              qex = CadastreExport(layer, 'parcelle', comptecommunal, feat['geo_parcelle'])
              File "C:/Users/992607/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_export.py", line 122, in __init__
              self.connectionParams = cadastre_common.getConnectionParameterFromDbLayer(self.layer)
              File "C:/Users/992607/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_common_base.py", line 111, in getConnectionParameterFromDbLayer
              if layer.providerType() == 'postgres':
             AttributeError: 'str' object has no attribute 'providerType'
```

-	Lorsque je clique sur le bouton de relevé de propriété :

```
2021-08-31T14:22:40     WARNING    Traceback (most recent call last):
              File "C:/Users/992607/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\dialogs\search_dialog.py", line 1215, in exportProprietaire
              qex = CadastreExport(layer, 'proprietaire', cc)
             TypeError: __init__() missing 1 required positional argument: 'comptecommunal'
```

**Environnement**
 - OS: Windows 10
 - Version de QGIS :  testé 3.8, 3.16 et 3.20
 - Version du plugin : 1.13.2

**Comment by Gustry** [comment]
First error fixed in 61dd434
