### ISSUE TITLE
MAJIC III 2021 - MemoryError Python

### ISSUE THREAD

**Issue by rldhont** [3liz/QgisCadastrePlugin#326]
**Description du bug**
Une erreur est survenue lors de l'éxécution du code Python:
```
MemoryError
Traceback (most recent call last):
  File "C:/Users/thomas.baron/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\dialogs\import_dialog.py", line 323, in processImport
    qi.importMajic()
  File "C:/Users/thomas.baron/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_import.py", line 411, in importMajic
    item['method']()
  File "C:/Users/thomas.baron/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_import.py", line 556, in importMajicIntoDatabase
    ) for x in a if x and x[0:3] == depdir
MemoryError
```

**Reproduire le bug**

1. Lancer un import avec des données MAJIC III 2021

**Log**

```
MemoryError
Traceback (most recent call last):
  File "C:/Users/thomas.baron/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\dialogs\import_dialog.py", line 323, in processImport
    qi.importMajic()
  File "C:/Users/thomas.baron/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_import.py", line 411, in importMajic
    item['method']()
  File "C:/Users/thomas.baron/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_import.py", line 556, in importMajicIntoDatabase
    ) for x in a if x and x[0:3] == depdir
MemoryError
```
**Environnement**
 - OS: Windows
 - Version de QGIS :  3.4.15-Madeira Madeira, e83d02e274 et 3.16.11-Hannover Hannover, 26cc1c762f
 - Version du plugin : 1.13.2
 - Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]

**Comment by rldhont** [comment]
Même erreur avec QGIS 3.16

**Comment by Gustry** [comment]
Lien avec 60bb92e pour la partie code et 848c09f170dc66800fc75a12fb650cc7d4347953 pour la documentation
