### ISSUE TITLE
Import données impossible en SQLite

### ISSUE THREAD

**Issue by M-Rick** [3liz/QgisCadastrePlugin#347]
**Description du bug**

J'ai tenté à plusieurs reprises d'importer un département complet depuis cette liste et le plug-in ne finalise jamais l'import.
https://cadastre.data.gouv.fr/data/dgfip-pci-vecteur/2022-01-01/edigeo/departements/

J'ai essayé avec QGIS 3.22.3 sur Windows 10 avec un Xeon depuis une nouvelle installation. Sur macOS X Mojave avec QGIS 3.16.16 et 3.22.3 et un Core i7, sur Ubuntu Linux 21.10 et QGIS 3.16.14.
J'ai déjà utilisé ce plug-in à de nombreuses reprises toujours sur des jeux de données départementaux et ça fonctionnait toujours très bien.
Ça ne bloque que si je tente d’importer un département complet, pas avec une commune.

**Log**

```
2022-02-19T22:32:32     WARNING    Traceback (most recent call last):
              File "/home/aymeric/.local/share/QGIS/QGIS3/profiles/default/python/plugins/cadastre/dialogs/import_dialog.py", line 327, in processImport
              qi.importEdigeo()
              File "/home/aymeric/.local/share/QGIS/QGIS3/profiles/default/python/plugins/cadastre/cadastre_import.py", line 753, in importEdigeo
              self.qc.checkDatabaseForExistingStructure()
              File "/home/aymeric/.local/share/QGIS/QGIS3/profiles/default/python/plugins/cadastre/dialogs/dialog_common.py", line 226, in checkDatabaseForExistingStructure
              getSearchTable = [a for a in self.dialog.db.tables() if a.name == searchTable]
              File "/usr/share/qgis/python/plugins/db_manager/db_plugins/plugin.py", line 548, in tables
              tables = self.connector.getTables(schema.name if schema else None, sys_tables)
              File "/usr/share/qgis/python/plugins/db_manager/db_plugins/spatialite/connector.py", line 177, in getTables
              vectors = self.getVectorTables(schema)
              File "/usr/share/qgis/python/plugins/db_manager/db_plugins/spatialite/connector.py", line 267, in getVectorTables
              c = self._get_cursor()
              File "/usr/share/qgis/python/plugins/db_manager/db_plugins/connector.py", line 114, in _get_cursor
              return self.connection.cursor()
             AttributeError: 'NoneType' object has no attribute 'cursor'
```

**Environnement**
 - OS: macOS, Linux, Windows
 - Version de QGIS :  3.16 / 3.22
 - Version du plugin : 1.13.5

[QGIS_2022-02-20-165232_MacBook-Air.cpu_resource.diag.txt](https://github.com/3liz/QgisCadastrePlugin/files/8104883/QGIS_2022-02-20-165232_MacBook-Air.cpu_resource.diag.txt)

Version de QGIS | 3.22.3-Białowieża | Révision du code | 1628765ec7
-- | -- | -- | --
Version de Qt | 5.15.2 |   |  
Version de Python | 3.9.5 |   |  
Version de GDAL/OGR | 3.3.2 |   |  
Version de Proj | 8.1.1 |   |  
Version de la base de données du registre EPSG | v10.028 (2021-07-07) |   |  
Version de GEOS | 3.9.1-CAPI-1.14.2 |   |  
Version de SQLite | 3.35.2 |   |  
Version de PDAL | 2.3.0 |   |  
Version du client PostgreSQL | 12.3 |   |  
Version de SpatiaLite | 5.0.1 |   |  
Version de QWT | 6.1.6 |   |  
Version de QScintilla2 | 2.11.5 |   |  
Version de l'OS | macOS 11.6 |   |  
  |   |   |  
Extensions Python actives |   |   |  
ORStools | 1.5.2 |   |  
QuickOSM | 2.0.1 |   |  
gban | 1.1 |   |  
QNEAT3 | 1.0.4 |   |  
amil | 1.1.1 |   |  
qgis_report_wizard | 1.0.1 |   |  
latlontools | 3.6.2 |   |  
OpenTripPlannerPlugin-master | 1.0 |   |  
anyways_impact_toolbox | 0.7.1 |   |  
spline | 0.2 |   |  
Qgis2threejs | 2.6 |   |  
mobilityareas | 0.2 |   |  
valhalla | 2.2.1 |   |  
GTFS-GO-master | 2.2.0 |   |  
ProjectPackager | 0.5.1 |   |  
GTFS_Loader | 1.0.0 |   |  
processing | 2.12.99 |   |  
sagaprovider | 2.12.99 |   |  
grassprovider | 2.12.99 |   |  
db_manager | 0.1.20 |   |  
MetaSearch | 0.3.5 |   |  
cadastre | 1.13.5 |   |  

Version de QGIS | 3.10.14-A Coruña | Branche de code de QGIS | Release 3.10
-- | -- | -- | --
Compilé avec Qt | 5.15.2 | Utilisant Qt | 5.15.2
Compilé avec GDAL/OGR | 3.2.2 | Utilisé avec GDAL/OGR | 3.2.2
Compilé avec GEOS | 3.9.0-CAPI-1.16.2 | Utilisé avec GEOS | 3.9.0-CAPI-1.16.2
Compilé avec SQLite | 3.34.1 | Fonctionne avec SQLite | 3.35.5
Version du client PostgreSQL | 13.2 (Ubuntu 13.2-1) | Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.6
Compilé avec PROJ | 7.2.1 | Fonctionne avec PROJ | Rel. 7.2.1, January 1st, 2021
Version de l'OS | Pop!_OS 21.10 |   |  
Extensions Python actives | cadastre;  LoadQSS;  MetaSearch;  db_manager;  processing |   |

**Comment by M-Rick** [comment]
J'ai essayé dans QGIS 2 que je n'avais plus utilisé depuis 4 ans, et ça a fonctionné à merveille avec les mêmes réglages !

```
INITIALISATION
* Copie du répertoire /Users/aymeric/.qgis2/python/plugins/cadastre/scripts/plugin 
0 s 
STRUCTURATION BDD
Création des tables 
Création des tables edigeo 
Ajout de la nomenclature 
0 s 
EDIGEO
Type de base : spatialite, Connexion: dep44.sqlite, Schéma: 
* Décompression des fichiers 
571 s 
Suppression des contraintes 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : DEBUT 
- suppression clefs primaires 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : FIN 
571 s 
* Import des fichiers EDIGEO dans la base 
- Import des fichiers via ogr2ogr 
- Import des relations (*.vec) 
- 1960 multipolygones mis à jours dans la base de données 
9039 s 
Mise en forme des données 
- FORMATAGE DONNEES : DEBUT 
- Suppression des données du lot '44' 
9039 s 
- index pour optimisation 
9039 s 
- geo_commune: utilisation de max et non distinct on pour compatibilite sqlite 
9109 s 
- geo_section 
9123 s 
- geo_subdsect 
9142 s 
- geo_parcelle 
9142 s 
- Indexes sur geo_parcelle et geo_commune pour optimisation 
9606 s 
- geo_subdfisc 
9651 s 
- geo_subdfisc_parcelle 
9651 s 
- geo_voiep 
9666 s 
- geo_numvoie 
9697 s 
- geo_numvoie_parcelle 
9697 s 
- geo_lieudit 
9740 s 
- geo_batiment 
9932 s 
- geo_batiment_parcelle 
9932 s 
- geo_zoncommuni 
10360 s 
- geo_tronfluv 
10373 s 
- geo_tronroute 
10376 s 
- geo_sym 
10376 s 
- geo_ptcanv 
10378 s 
- geo_borne 
10529 s 
- geo_borne_parcelle 
10529 s 
- geo_croix 
10645 s 
- geo_croix_parcelle 
10645 s 
- geo_symblim 
10727 s 
- geo_symblim_parcelle 
10785 s 
- geo_tpoint 
10844 s 
- geo_tpoint_commune 
10846 s 
- geo_tline 
10909 s 
- geo_tline_commune 
10909 s 
- geo_tsurf 
10943 s 
- geo_tsurf_commune 
10943 s 
- suppression des index temporaires 
10947 s 
- analyses 
10955 s 
- FORMATAGE DONNEES : FIN 
10973 s 
Placement des étiquettes 
11492 s 
Création des indexes spatiaux 
- attributes 
11957 s 
12051 s 
Ajout des contraintes 
- CREATION DES CONTRAINTES D'INTEGRITEES : DEBUT 
- création clé primaire 
- création clé étrangère 
- CREATION DES CONTRAINTES D'INTEGRITEES : FIN 
12094 s 
Ajout de la table parcelle_info 
12423 s 
12476 s 
FINALISATION
12736 s 
```

Version de QGIS | 2.18.28 | Branche de code de QGIS | Release 2.18
-- | -- | -- | --
Compilé avec Qt | 4.8.6 | Utilisant Qt | 4.8.6
Compilé avec GDAL/OGR | 2.1.3 | Utilisé avec GDAL/OGR | 2.1.3
Compilé avec GEOS | 3.6.2-CAPI-1.10.2 | Utilisé avec GEOS | 3.6.1-CAPI-1.10.1 r0
Version du client PostgreSQL | 9.4.15 | Version de SpatiaLite | 4.2.0
Version de QWT | 6.1.3 | Version de PROJ.4 : | 492
Version de QScintilla2 | 2.9.3 |   |
