### ISSUE TITLE
La fonction next_git_tag() nuie au travail sur le code

### ISSUE THREAD

**Issue by MaelREBOUX** [3liz/QgisCadastrePlugin#374]
**Description du bug**

Bonjour @Gustry,

Nous travaillons sur #370 et #372 et nous avons des difficultés à tester les modifications.
En effet le commit https://github.com/3liz/QgisCadastrePlugin/commit/5b8edfd5f3b9401d96ca62e92535f1bbbf275d3a introduit des fonctions qui font appel à `git describe...`. Or si on prend / copie / alias le répertoire `cadastre` du projet pour qu'il soit visible : cela produit immanquablement l'erreur suivante :

```
Traceback (most recent call last):
  File "C:/Users/m.reboux/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\cadastre_menu.py", line 259, in open_import_dialog
    dialog = CadastreImportDialog(self.iface)
  File "C:/Users/m.reboux/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\dialogs\import_dialog.py", line 36, in __init__
    self.setWindowTitle('{} {}'.format(self.windowTitle(), set_window_title()))
  File "C:/Users/m.reboux/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\tools.py", line 90, in set_window_title
    return 'next {}'.format(next_git_tag())
  File "C:/Users/m.reboux/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cadastre\tools.py", line 73, in next_git_tag
    tag = git_show.communicate()[0].partition('\n')[0]
  File "C:\PROGRA~1\QGIS\3.16\apps\Python37\lib\subprocess.py", line 920, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\PROGRA~1\QGIS\3.16\apps\Python37\lib\subprocess.py", line 1267, in _communicate
    stderr = stderr[0]
IndexError: list index out of range

```

**Proposition de résolution**

Je suppose que les développeurs "pros" (je ne m'inclue pas dedans) travaillent dans des environnements de développement correctement configurés.
Pour autant je ne comprend pas comment la version actuelle du plugin (v 1.14.2) téléchargée depuis le gestionnaire de plugin fonctionne sachant qu'il n'y a pas le répertoire supérieur et que ce n'est PAS un repo git fonctionnel ??

Je vais donc proposer une gestion de l'erreur si on tente un `git describe...`.

**Environnement**
 - OS: Windows 10
 - Version de QGIS :  3.10 / 3.16
 - Version du plugin :  code source issu du clone de dépôt

**Comment by MaelREBOUX** [comment]
Testé et validé. Ok pour merge selon moi.

**Comment by MaelREBOUX** [comment]
merci @Gustry
