### ISSUE TITLE
Reprojection lors de l'import vers EPSG4326

### ISSUE THREAD

**Issue by cotegeo** [3liz/QgisCadastrePlugin#422]
Bonjour,

J'ai rencontré le pb suivant quand j'ai essayé d'importer des données majic dans une base de données PostGre/PostGis. 

J'ai les données EDIGEO et les fichiers majic. Les données natives sont en EPSG:2154, et je cherche à les importer en 4326.
Dans le formulaire d'import je met 2154 dans la projection source et 4326 dans le champ cible.

Sauf qu'une fois que l'import est terminé et que l'on fait remonter les géométries dans qGIS (via une couche PostGreSQL), les parcelles se retrouvent au large de la Somalie. Il semble qu'il y ait qque part une inversion des données de longitude et de latitude.

Quand on demande à charger les données dans qGIS avec le module, le module renvoie :

`Une erreur est survenue lors de l'éxécution du code Python: 

IndexError: list index out of range 
Traceback (most recent call last):
  File "/home/sylvain/.local/share/QGIS/QGIS3/profiles/default/python/plugins/cadastre/dialogs/cadastre_load_dialog.py", line 107, in onProcessLoadingClicked
    self.ql.processLoading()
  File "/home/sylvain/.local/share/QGIS/QGIS3/profiles/default/python/plugins/cadastre/cadastre_loading.py", line 434, in processLoading
    cTable = cTableList[0]
IndexError: list index out of range`

Merci pour vos retours

Sylvain Becquaert

**Comment by MaelREBOUX** [comment]
Vu l’ancienneté de ce ticket, je me permet de le clore.
