### ISSUE TITLE
Erreur lors de l'import sans fichier MAJIC

### ISSUE THREAD

**Issue by samuelDeom** [3liz/QgisCadastrePlugin#437]
**Description du bug**

Lorsque je cherche à importer des fichier au format EDIGEO, après m'avoir avertit qu'il manque les fichiers MAJIC et m'avoir demandé confirmation d'importer tout de même les feuilles, le plug in plante.

**Reproduire le bug**

1. Ouvrir la fenêtre...
2. Lancer l'import...

**Log**

IndexError: list index out of range 
Traceback (most recent call last):
  File "/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cadastre/dialogs/import_dialog.py", line 323, in processImport
    qi.importMajic()
  File "/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cadastre/cadastre_import.py", line 415, in importMajic
    item['method']()
  File "/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cadastre/cadastre_import.py", line 527, in import_majic_into_database
    f_dep = list(dep_dirs.keys())[0][0:2]
IndexError: list index out of range

Version de Python : 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
Version de QGIS : 3.28.14-Firenze Firenze, b09131c5125 

Chemin Python :
/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Cadastral_Divisions-main
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python
/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools
/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools
/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2streetview
/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/res
.
/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/joinmultiplelines
/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SwapVectorDirection
/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing
/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/ext_libs
/Users/samuel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/shapetools/ext-libs

**Environnement**
 - OS: OSX
 - Version de QGIS : 3.28.14-Firenze, b09131c5125
 - Version du plugin : Version 1.19.0

**Comment by Gustry** [comment]
Avez-vous essayé avec la dernière version de l'extension Cadastre ?

**Comment by BHaasCCCE** [comment]
Bonjour, oui mon plugin est à jour. J'ai oublié de le préciser mais à l'inverse de samuelDeom l'erreur se produit uniquement lorsque je veux intégrer les fichier MAJIC.

**Comment by Gustry** [comment]
Quelle est l'erreur précise ? Donc pas la même que @samuelDeom ?

**Comment by BHaasCCCE** [comment]
J'avais la même que @samuelDeom mais en suppriment la bdd sqlite et en créant un nouvelle l'erreur de ne se produit plus.

J'ai vu que la dernière maj du plugin nous demandait le fichier topo donc je suis aller le récupéré sur le site du gouvernement.
Ce coup là lors de l'intégration le plug in détecte bien les fichiers EDIGEO et MAJIC mais il y a tout de même un message d'erreur:

INITIALISATION
* Copie du répertoire C:\Users\b.haas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cadastre\scripts/plugin 
0 s 
MAJIC
Suppression des contraintes 
0 s 
- SUPPRESSION DES CONTRAINTES D'INTEGRITEES : DEBUT 
0 s 
- suppression clefs primaires 
0 s 
Suppression des indexes 
0 s 
Import des fichiers MAJIC 
bati 
C:/Users/b.haas/Desktop/CC CATTENOM ET ENVIRONS/CC CATTENOM ET ENVIRONS\ART.DC21.W24570.BATI.A2024.N000754 
topo 
C:/Users/b.haas/Desktop/CC CATTENOM ET ENVIRONS/CC CATTENOM ET ENVIRONS\topo-fichier-des-entites-topographiques.xlsx 
lloc 
C:/Users/b.haas/Desktop/CC CATTENOM ET ENVIRONS/CC CATTENOM ET ENVIRONS\ART.DC21.W24570.LLOC.A2024.N000754 
nbat 
C:/Users/b.haas/Desktop/CC CATTENOM ET ENVIRONS/CC CATTENOM ET ENVIRONS\ART.DC21.W24570.NBAT.A2024.N000754 
pdll 
C:/Users/b.haas/Desktop/CC CATTENOM ET ENVIRONS/CC CATTENOM ET ENVIRONS\ART.DC21.W24570.PDLL.A2024.N000754 
prop 
C:/Users/b.haas/Desktop/CC CATTENOM ET ENVIRONS/CC CATTENOM ET ENVIRONS\ART.DC21.W24570.PROP.A2024.N000754 
138 s 
Mise en forme des données 
138 s 
- FORMATAGE DONNEES : DEBUT 
138 s 
- Traitement: parcelle 
140 s 
- Traitement: suf 
142 s 
- Traitement: sufexoneration 
143 s 
- Traitement: suftaxation 
144 s 
- Traitement: local00 
144 s 
- Traitement: local10 
147 s 
- Traitement: pev 
148 s 
- Traitement: pevexoneration 
148 s 
- Traitement: pevexoneration_imposable 
148 s 
- Traitement: pevexoneration_imposee 
148 s 
- Traitement: pevtaxation 
149 s 
- Traitement: pevprincipale 
149 s 
- Traitement: pevprofessionnelle 
149 s 
- Traitement: 
149 s 
- Traitement: pevdependances 
149 s 
- Traitement: commune_majic 
149 s 
- Traitement: proprietaire 
151 s 
- création: comptecommunal à partir de proprietaire 
151 s 
- Traitement: pdl 
151 s 
- Traitement: parcellecomposante 
151 s 
- Traitement: lots 
151 s 
- Traitement: lotslocaux 
151 s 
- Traitement: commune 
Erreur rencontrée pour la requête: 
-- Traitement: commune INSERT INTO commune ( commune, geo_commune, annee, ccodep, ccodir, ccocom, clerivili, libcom, typcom, ruract, carvoi, indpop, poprel, poppart, popfict, annul, dteannul, dtecreart, codvoi, typvoi, indldnbat, motclas, lot ) SELECT REPLACE(SUBSTR(tmp,1,6),' ', '0') AS commune, REPLACE(SUBSTR(tmp,1,6),' ', '0') AS geo_commune, '2024', SUBSTR(tmp,1,2) AS ccodep, SUBSTR(tmp,3,1) AS ccodir, SUBSTR(tmp,4,3) AS ccocom, SUBSTR(tmp,11,1) AS clerivili, SUBSTR(tmp,12,30) AS libcom, CASE WHEN trim(SUBSTR(tmp,43,1))='' THEN NULL ELSE trim(SUBSTR(tmp,43,1)) END AS typcom, SUBSTR(tmp,46,1) AS ruract, SUBSTR(tmp,49,1) AS carvoi, SUBSTR(tmp,50,1) AS indpop, CASE WHEN trim(SUBSTR(tmp,53,7))='' THEN NULL ELSE CAST(trim(SUBSTR(tmp,53,7)) AS float) END AS poprel, CAST(SUBSTR(tmp,60,7) AS float) AS poppart, CAST(SUBSTR(tmp,67,7) AS float) AS popfict, SUBSTR(tmp,74,1) AS annul, SUBSTR(tmp,75,7) AS dteannul, SUBSTR(tmp,82,7) AS dtecreart, SUBSTR(tmp,104,5) AS codvoi, SUBSTR(tmp,109,1) AS typvoi, SUBSTR(tmp,110,1) AS indldnbat, SUBSTR(tmp,113,8) AS motclas, 'CCCE' as lot FROM fanr WHERE SUBSTR(tmp,4,3) != ' ' AND trim(SUBSTR(tmp,7,4))=''
Erreur 
no such table: fanr
FINALISATION

**Comment by samuelDeom** [comment]
@BHaasCCCE : je n'ai pas trouvé l'erreur et j'ai contourné le problème en intégrant les fichiers PCI au format DXF façon spaghetti, ce qui suffisait pour mon besoin.
Je n'ai pas réessayé depuis.

**Comment by mdouchin** [comment]
> * Erreur rencontrée pour la requête:
>       -- Traitement: commune INSERT INTO commune ( commune, geo_commune, annee, ccodep, ccodir, ccocom, clerivili, libcom, typcom, ruract, carvoi, indpop, poprel, poppart, popfict, annul, dteannul, dtecreart, codvoi, typvoi, indldnbat, motclas, lot ) SELECT REPLACE(SUBSTR(tmp,1,6),' ', '0') AS commune, REPLACE(SUBSTR(tmp,1,6),' ', '0') AS geo_commune, '2024', SUBSTR(tmp,1,2) AS ccodep, SUBSTR(tmp,3,1) AS ccodir, SUBSTR(tmp,4,3) AS ccocom, SUBSTR(tmp,11,1) AS clerivili, SUBSTR(tmp,12,30) AS libcom, CASE WHEN trim(SUBSTR(tmp,43,1))='' THEN NULL ELSE trim(SUBSTR(tmp,43,1)) END AS typcom, SUBSTR(tmp,46,1) AS ruract, SUBSTR(tmp,49,1) AS carvoi, SUBSTR(tmp,50,1) AS indpop, CASE WHEN trim(SUBSTR(tmp,53,7))='' THEN NULL ELSE CAST(trim(SUBSTR(tmp,53,7)) AS float) END AS poprel, CAST(SUBSTR(tmp,60,7) AS float) AS poppart, CAST(SUBSTR(tmp,67,7) AS float) AS popfict, SUBSTR(tmp,74,1) AS annul, SUBSTR(tmp,75,7) AS dteannul, SUBSTR(tmp,82,7) AS dtecreart, SUBSTR(tmp,104,5) AS codvoi, SUBSTR(tmp,109,1) AS typvoi, SUBSTR(tmp,110,1) AS indldnbat, SUBSTR(tmp,113,8) AS motclas, 'CCCE' as lot FROM fanr WHERE SUBSTR(tmp,4,3) != ' ' AND trim(SUBSTR(tmp,7,4))=''
>       Erreur
>       no such table: fanr

Bonjour,

Le plugin version 2.0.0 n'utilise normalement plus de table `fanr`, qui a été remplacée par la table `topo`.
@BHaasCCCE Avez-vous bien choisi la version **2024** et le millésime **2024** dans les options d'import ?

**Comment by BHaasCCCE** [comment]
@mdouchin merci pour votre aide l'intégration semble avoir fonctionné avec changeant l'année de la version du format !
Maintenant il ne me reste plus qu'a trouvé comment accéder aux années de construction des bâtiments. Encore merci !

**Comment by Gustry** [comment]
Je clos, merci du retour.
